on: push
jobs:
  Build_Project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: javac *.java
  Run_Basic_IO_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: javac *.java
      - run: java Main < .github\workflows\test1.txt
      - run: java Main < .github\workflows\test2.txt
      - run: java Main < .github\workflows\test3.txt
      - run: java Main < .github\workflows\test4.txt

  